### ISSUE TITLE
Not enable to point subdomain name to cloudflare

### ISSUE THREAD

**Issue by Raphjacksun7** [roleupjobboard/documentation#1]
![Capture](https://user-images.githubusercontent.com/33360402/126573776-1da92b35-3085-4274-879d-931cb3867bfa.PNG)
![Capture5](https://user-images.githubusercontent.com/33360402/126573795-caec68d8-dd93-4e38-9fe0-d4d01d702855.PNG)

**Comment by gsempe** [comment]
Hi,

I just noticed your question. Even though it has probably no value anymore for you, I decided to share the answer here because it is important for future users.

On CNAME records, Cloudflare has an option called "proxied". This option has to be removed to get your custom domain name working.

In the screenshot below the option "proxied" is activated. It has be deactivated be to work with RoleUp.

![cloudflare-proxied](https://user-images.githubusercontent.com/1011479/193447445-5912e3fc-1b7e-4e87-9516-1d92ee5860dc.jpg)
